# Generated by Django 5.0.6 on 2024-05-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=50)),
                ('passing_year', models.PositiveIntegerField()),
                ('study', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('duration_in_months', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileImg')),
                ('about_you', models.TextField(max_length=1000)),
                ('education', models.ManyToManyField(to='generateResume.education')),
                ('experience', models.ManyToManyField(to='generateResume.experience')),
                ('skills', models.ManyToManyField(to='generateResume.skills')),
            ],
        ),
    ]
