# Generated by Django 5.0.6 on 2024-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateResume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, upload_to='profileImg/'),
        ),
    ]
