# Generated by Django 5.0.6 on 2024-05-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateResume', '0002_alter_resume_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='generateResume.resume'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='generateResume.resume'),
        ),
        migrations.AddField(
            model_name='skills',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='generateResume.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='inst_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='study',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration_in_months',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about_you',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='locality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
