# Generated by Django 5.0.6 on 2024-05-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateResume', '0003_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='generateResume.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='generateResume.resume'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='generateResume.resume'),
        ),
    ]
