# Generated by Django 5.0.6 on 2024-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateResume', '0004_alter_education_resume_alter_experience_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='generateResume.skill'),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
