# Generated by Django 5.0.6 on 2024-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateResume', '0005_skill_resume_skills_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration_in_months',
            field=models.IntegerField(),
        ),
    ]
